# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push]

jobs:
  build-linux:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    container: arm64v8/eclipse-temurin:17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :desktop-merge:jpackage --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Craft Linux Build ${{ github.run_number }}
          path: desktop-merge/build/dist
  build-linux-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv6l, armv7l, aarch64]
        include:
          - arch: armv6l
            cpu: arm1176
            base_image: raspios_lite:latest
            cpu_info: raspberrypi_zero_w
          - arch: armv7l
            cpu: cortex-a7
            base_image: raspios_lite:latest
            cpu_info: raspberrypi_3b
          - arch: aarch64
            cpu: cortex-a53
            base_image: raspios_lite_arm64:latest
            cpu_info: raspberrypi_zero2_w_arm64_w
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: ${{ matrix.base_image }}
          cpu: ${{ matrix.cpu }}
          cpu_info: ${{ matrix.cpu_info }}
          copy_artifact_path: build/dist/
          copy_artifact_dest: build/dist/
          commands: |
              sudo apt install openjdk-17
              chmod +x ./gradlew
              ./gradlew :desktop-merge:jpackage --info
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Craft Linux ARM64 Build ${{ github.run_number }}
          path: desktop-merge/build/dist
  build-macos:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [macOS-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :desktop-merge:jpackage --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Craft MacOS Build ${{ github.run_number }}
          path: desktop-merge/build/dist
  build-windows:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: cmd /c "gradlew.bat jpackage --info"
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Ultreon Craft Windows Build ${{ github.run_number }}
          path: desktop-merge/build/dist
